#!/bin/bash
# OTA push to the oi device via WebREPL.
# Pushes any combination of boot.py / main.py / lib/*.py to the device,
# optionally followed by a soft reset.
#
# Requires:
#   - Device on wifi at OI_HOST (default gateway.local)
#   - WebREPL running on port 8266 (boot.py starts it)
#   - WEBREPL_PASSWORD in ~/.oi/secrets/firmware/oi-v1/webrepl.env
#
# Usage:
#   ./push.sh main.py                # push one file
#   ./push.sh boot.py main.py        # push several
#   ./push.sh --all                  # push boot.py + main.py + everything in lib/
#   ./push.sh --reset main.py        # push then soft-reset device
#   ./push.sh --dry-run --all        # show what would be pushed; no network calls
#   ./push.sh --status --all         # print resolved config + target list, then exit
#
# After a push, the new code only takes effect on the next reset/import.
# Use --reset for the convenient "edit → push → see it run" loop.

set -e

OI_HOST="${OI_HOST:-gateway.local}"
OI_WEBREPL_PORT="${OI_WEBREPL_PORT:-8266}"
ENV_FILE="${OI_ENV_FILE:-$HOME/.oi/secrets/firmware/oi-v1/webrepl.env}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FIRMWARE_DIR="$(cd "$SCRIPT_DIR/../firmware" && pwd)"
WEBREPL_CLI="${OI_WEBREPL_CLI:-$SCRIPT_DIR/webrepl_cli.py}"

DO_RESET=false
ALL=false
DRY_RUN=false
STATUS_ONLY=false
TARGETS=()

for arg in "$@"; do
    case "$arg" in
        --reset)    DO_RESET=true ;;
        --all)      ALL=true ;;
        --dry-run|-n)
                    DRY_RUN=true ;;
        --status)   STATUS_ONLY=true ;;
        --help|-h)
            sed -n '2,26p' "$0"
            exit 0
            ;;
        *)          TARGETS+=("$arg") ;;
    esac
done

if $ALL; then
    TARGETS=("boot.py" "main.py")
    for f in "$FIRMWARE_DIR"/lib/*.py; do
        TARGETS+=("lib/$(basename "$f")")
    done
fi

if [[ ${#TARGETS[@]} -eq 0 ]] && ! $STATUS_ONLY; then
    echo "Nothing to push. Pass file names or --all." >&2
    exit 1
fi

NEEDS_WEBREPL=true
if $DRY_RUN || $STATUS_ONLY; then
    NEEDS_WEBREPL=false
fi

if $NEEDS_WEBREPL; then
    if [[ ! -f "$ENV_FILE" ]]; then
        echo "ERROR: $ENV_FILE not found. Generate it with the firmware secrets pipeline." >&2
        exit 1
    fi
    # shellcheck disable=SC1090
    source "$ENV_FILE"

    if [[ -z "${WEBREPL_PASSWORD:-}" ]]; then
        echo "ERROR: WEBREPL_PASSWORD not set in $ENV_FILE" >&2
        exit 1
    fi

    if [[ ! -f "$WEBREPL_CLI" ]]; then
        echo "ERROR: $WEBREPL_CLI not found" >&2
        exit 1
    fi
fi

# Resolve firmware version string from current git state.
GIT_HASH="$(git -C "$FIRMWARE_DIR/.." rev-parse --short HEAD 2>/dev/null || echo dev)"
GIT_DIRTY=""
if ! git -C "$FIRMWARE_DIR/.." diff --quiet 2>/dev/null \
        || ! git -C "$FIRMWARE_DIR/.." diff --cached --quiet 2>/dev/null; then
    GIT_DIRTY="+"
fi
VERSION_VALUE="${GIT_HASH}${GIT_DIRTY}"

# Regenerate firmware/version.py from the current git short hash so the device
# can render which commit it is running. Always pushed first.
if ! $DRY_RUN && ! $STATUS_ONLY; then
    cat > "$FIRMWARE_DIR/version.py" <<EOF
# Generated by scripts/push.sh — do not hand-edit.
VERSION = "${VERSION_VALUE}"
EOF
fi
TARGETS=("version.py" "${TARGETS[@]}")

if $STATUS_ONLY; then
    echo "[oi push] status"
    echo "  host: ${OI_HOST}:${OI_WEBREPL_PORT}"
    echo "  firmware: $FIRMWARE_DIR"
    echo "  webrepl_cli: $WEBREPL_CLI"
    echo "  env_file: $ENV_FILE"
    echo "  version: $VERSION_VALUE"
    echo "  dry_run: $DRY_RUN"
    echo "  reset: $DO_RESET"
    echo "  targets (${#TARGETS[@]}):"
    for t in "${TARGETS[@]}"; do
        echo "    - $t"
    done
    exit 0
fi

push_one() {
    local rel="$1"
    local local_path="$FIRMWARE_DIR/$rel"
    if [[ ! -f "$local_path" ]]; then
        echo "  ! missing: $local_path" >&2
        return 1
    fi
    local remote_path="$rel"
    if $DRY_RUN; then
        echo "  dry-run: push $rel -> ${OI_HOST}:/$remote_path"
        return 0
    fi

    echo "  push: $rel"
    # Filter out the line where webrepl_cli.py echoes the password ("passwd:...")
    local output rc
    set +e
    output=$(python3 "$WEBREPL_CLI" -p "$WEBREPL_PASSWORD" \
        "$local_path" \
        "$OI_HOST:/$remote_path" 2>&1)
    rc=$?
    set -e
    printf '%s\n' "$output" | grep -v -E '^op:|passwd:' || true
    if [[ $rc -ne 0 ]]; then
        echo "ERROR: WebREPL upload failed for $rel (exit $rc)" >&2
        return "$rc"
    fi
}

echo "[oi push] target=$OI_HOST  files=${#TARGETS[@]}"
for t in "${TARGETS[@]}"; do
    push_one "$t"
done

if $DO_RESET; then
    if $DRY_RUN; then
        echo "[oi push] dry-run: would soft-reset device via webrepl"
    else
        echo "[oi push] soft-resetting device via webrepl..."
        set +e
        reset_output=$(python3 "$WEBREPL_CLI" -p "$WEBREPL_PASSWORD" \
            --command "import machine; machine.soft_reset()" \
            "$OI_HOST" 2>&1)
        reset_rc=$?
        set -e
        printf '%s\n' "$reset_output" | grep -v -E '^op:|passwd:' | tail -3 || true
        if [[ $reset_rc -ne 0 ]]; then
            echo "ERROR: WebREPL reset failed (exit $reset_rc)" >&2
            exit "$reset_rc"
        fi
    fi
fi

echo "[oi push] done."
